### ISSUE TITLE
this is an impossible task

### ISSUE THREAD

**Issue by darkBuddha** [romcheckfail/shodan-ip-block-list#2]
... although a nice intention.

Check out the massive IP range they use, thanks to talkative MySQL: 

https://www.shodan.io/search?query=is+not+allowed+to+connect+to+this+MySQL+server

**Comment by Jas0n99** [comment]
That's very interesting... I did a lookup of a couple pages worth of IPs, and either they are randomly generated (as they come from all over the world), or Shodan is illegally using people's systems without their knowledge. There were some that were K-12 networks, cell networks, residential DSL, etc...

Not one resolved to a xxxxxx.shodan.io domain...

**Comment by sv0** [comment]
@Jas0n99  It seems  Shodan replaces its IP addresses with some random ones.
